import base from './vitest.unit.config.js';
import { defineConfig, mergeConfig } from 'vitest/config';

const unitOwnedCoverageFiles = [
  'src/shared/apiKeyBatch.ts',
  'src/shared/proxyLogMeta.js',
  'src/shared/sitePrimaryUrl.js',
  'src/shared/tokenRouteContract.js',
  'src/shared/updateCenterReminder.ts',
  'src/server/proxy-core/formats/configuredProtocolAdapter.ts',
  'src/server/proxy-core/formats/geminiProtocolFacade.ts',
  'src/server/proxy-core/formats/openaiChat.ts',
  'src/server/proxy-core/formats/protocolAdapters.ts',
  'src/server/proxy-core/formats/registry.ts',
  'src/server/proxy-core/runtime/codexWebsocketSessionStore.ts',
  'src/server/services/alertRules.ts',
  'src/server/services/apiKeyBatch.ts',
  'src/server/services/brandMatcher.ts',
  'src/server/services/checkinRewardParser.ts',
  'src/server/services/proxyBilling.ts',
  'src/server/services/proxyChannelRetry.ts',
  'src/server/services/proxyLogMessage.ts',
  'src/server/services/routeRoutingStrategy.ts',
  'src/server/services/shared/apiKeyBatchCore.ts',
  'src/server/services/siteDetector.ts',
  'src/server/services/statsShared.ts',
  'src/server/services/upstreamRequestBuilder.ts',
  'src/server/services/urlNormalization.ts',
  'src/server/shared/inputFileDataUrl.ts',
  'src/server/shared/logCleanupRetentionDays.ts',
  'src/server/transformers/anthropic/messages/outbound.ts',
  'src/server/transformers/canonical/continuationBridge.ts',
  'src/server/transformers/canonical/request.ts',
  'src/server/transformers/canonical/tools.ts',
  'src/server/transformers/gemini/generate-content/outbound.ts',
  'src/server/transformers/openai/chat/outbound.ts',
  'src/server/transformers/openai/chat/usage.ts',
  'src/server/transformers/openai/responses/inbound.ts',
  'src/server/transformers/openai/responses/outbound.ts',
  'src/server/transformers/openai/responses/usage.ts',
  'src/server/transformers/shared/endpointCompatibility.ts',
  'src/server/transformers/shared/protocolModel.ts',
  'src/web/components/mobileLayout.ts',
  'src/web/lib/utils.ts',
  'src/web/pages/helpers/accountConnection.ts',
  'src/web/pages/helpers/accountVerifyFeedback.ts',
  'src/web/pages/helpers/accountsPanelStyle.ts',
  'src/web/pages/helpers/defaultConnectionSegment.ts',
  'src/web/pages/helpers/fuzzySearch.ts',
  'src/web/pages/helpers/generateDownstreamSkKey.ts',
  'src/web/pages/helpers/modelsMarketplaceMetadata.ts',
  'src/web/pages/helpers/progressiveRender.ts',
  'src/web/pages/helpers/proxyLogPathMeta.ts',
  'src/web/pages/helpers/routeListVisibility.ts',
  'src/web/pages/helpers/routingProfiles.ts',
  'src/web/pages/helpers/rowSelection.ts',
  'src/web/pages/helpers/zeroChannelRoutes.ts',
  'src/web/pages/token-routes/priorityBuckets.ts',
  'src/web/pages/token-routes/priorityRail.ts',
  'src/web/pages/token-routes/routeGraphConnections.ts',
  'src/web/pages/token-routes/routeGraphEditorInteractions.ts',
  'src/web/pages/token-routes/routeGraphRegistry.ts',
  'src/web/pages/token-routes/routeGraphSnapshot.ts',
  'src/web/pages/token-routes/routeGraphViewModel.ts',
  'src/web/pages/token-routes/routingStrategy.ts',
  'src/web/pages/token-routes/sortingStrategies.ts',
  'src/web/pages/token-routes/useRouteChannels.ts',
  'src/web/pages/token-routes/utils.ts',
];

export default mergeConfig(base, defineConfig({
  test: {
    coverage: {
      provider: 'v8',
      reporter: ['text', 'html', 'json-summary', 'json'],
      include: unitOwnedCoverageFiles,
      exclude: [
        'src/**/*.test.{ts,tsx,js,jsx}',
        'src/**/*.architecture.test.{ts,tsx,js,jsx}',
        'src/**/*.live.test.{ts,tsx,js,jsx}',
        'src/**/__tests__/**',
      ],
      thresholds: {
        lines: 100,
        functions: 100,
        branches: 0,
        statements: 100,
      },
    },
  },
}));
