import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import type {
  LogicalColumnType,
  SchemaContract,
  SchemaContractColumn,
  SchemaContractForeignKey,
  SchemaContractIndex,
  SchemaContractUnique,
} from './schemaContract.js';

export interface GeneratedDialectArtifacts {
  mysqlBootstrap: string;
  postgresBootstrap: string;
  mysqlUpgrade: string;
  postgresUpgrade: string;
}

export type MysqlIndexPrefixRequirementMap = Record<string, Record<string, boolean>>;

type Dialect = 'mysql' | 'postgres';
type SqlDialect = 'sqlite' | Dialect;
type SqlGenerationOptions = {
  mysqlIndexPrefixRequirements?: MysqlIndexPrefixRequirementMap;
};
type ControlledReplacement = 'route-graph-token-routes';

function resolveDbDir(): string {
  return dirname(fileURLToPath(import.meta.url));
}

export function resolveGeneratedArtifactPath(filename: string): string {
  return resolve(resolveDbDir(), 'generated', filename);
}

function quoteIdentifier(dialect: SqlDialect, identifier: string): string {
  return dialect === 'mysql' ? `\`${identifier}\`` : `"${identifier}"`;
}

function quoteQualifiedIdentifier(dialect: SqlDialect, tableName: string, columnName: string): string {
  return `${quoteIdentifier(dialect, tableName)}.${quoteIdentifier(dialect, columnName)}`;
}

function escapeMysqlTextPrefix(columnType: LogicalColumnType): string {
  return columnType === 'text' ? '(191)' : '';
}

function resolveMysqlIndexPrefix(
  tableName: string,
  columnName: string,
  contract: SchemaContract,
  options?: SqlGenerationOptions,
): string {
  const override = options?.mysqlIndexPrefixRequirements?.[tableName]?.[columnName];
  if (override !== undefined) {
    return override ? '(191)' : '';
  }

  const column = contract.tables[tableName]?.columns[columnName];
  return column ? escapeMysqlTextPrefix(column.logicalType) : '';
}

function mapColumnType(dialect: SqlDialect, columnName: string, column: SchemaContractColumn): string {
  if (dialect === 'sqlite') {
    switch (column.logicalType) {
      case 'boolean':
      case 'integer':
        return 'INTEGER';
      case 'real':
        return 'REAL';
      case 'datetime':
      case 'json':
      case 'text':
      default:
        return 'TEXT';
    }
  }

  if (dialect === 'mysql') {
    switch (column.logicalType) {
      case 'boolean':
        return 'BOOLEAN';
      case 'integer':
        return column.primaryKey && columnName === 'id' ? 'INT AUTO_INCREMENT' : 'INT';
      case 'real':
        return 'DOUBLE';
      case 'datetime':
        return 'VARCHAR(191)';
      case 'json':
        return 'JSON';
      case 'text':
        return column.primaryKey || column.defaultValue != null ? 'VARCHAR(191)' : 'TEXT';
      default:
        return 'TEXT';
    }
  }

  switch (column.logicalType) {
    case 'boolean':
      return 'BOOLEAN';
    case 'integer':
      return column.primaryKey && columnName === 'id' ? 'INTEGER GENERATED BY DEFAULT AS IDENTITY' : 'INTEGER';
    case 'real':
      return 'DOUBLE PRECISION';
    case 'datetime':
      return 'TEXT';
    case 'json':
      return 'JSONB';
    case 'text':
    default:
      return 'TEXT';
  }
}

function formatDefaultValue(dialect: SqlDialect, column: SchemaContractColumn): string {
  if (column.defaultValue == null || column.primaryKey) {
    return '';
  }

  if (column.logicalType === 'datetime') {
    if (dialect === 'sqlite') {
      return " DEFAULT (datetime('now'))";
    }
    if (dialect === 'mysql') {
      return " DEFAULT (DATE_FORMAT(NOW(), '%Y-%m-%d %H:%i:%s'))";
    }
    return " DEFAULT to_char(timezone('UTC', CURRENT_TIMESTAMP), 'YYYY-MM-DD HH24:MI:SS')";
  }

  if (column.logicalType === 'boolean') {
    return ` DEFAULT ${column.defaultValue.toLowerCase()}`;
  }

  return ` DEFAULT ${column.defaultValue}`;
}

function buildColumnDefinition(
  dialect: SqlDialect,
  columnName: string,
  column: SchemaContractColumn,
): string {
  const sqlType = mapColumnType(dialect, columnName, column);
  const notNull = column.notNull ? ' NOT NULL' : '';
  const defaultValue = formatDefaultValue(dialect, column);
  const primaryKey = column.primaryKey ? ' PRIMARY KEY' : '';
  return `${quoteIdentifier(dialect, columnName)} ${sqlType}${notNull}${defaultValue}${primaryKey}`;
}

function buildForeignKeyClause(dialect: SqlDialect, foreignKey: SchemaContractForeignKey): string {
  const sourceColumns = foreignKey.columns.map((column) => quoteIdentifier(dialect, column)).join(', ');
  const targetColumns = foreignKey.referencedColumns.map((column) => quoteIdentifier(dialect, column)).join(', ');
  const onDelete = foreignKey.onDelete ? ` ON DELETE ${foreignKey.onDelete.toUpperCase()}` : '';
  return `FOREIGN KEY (${sourceColumns}) REFERENCES ${quoteIdentifier(dialect, foreignKey.referencedTable)}(${targetColumns})${onDelete}`;
}

function sortTableNamesForCreation(contract: SchemaContract): string[] {
  const ordered: string[] = [];
  const visited = new Set<string>();
  const visiting = new Set<string>();
  const tableNames = Object.keys(contract.tables).sort((left, right) => left.localeCompare(right, 'en'));

  const dependencies = new Map<string, string[]>();
  for (const tableName of tableNames) {
    const referencedTables = contract.foreignKeys
      .filter((foreignKey) => foreignKey.table === tableName)
      .map((foreignKey) => foreignKey.referencedTable)
      .filter((referencedTable) => referencedTable !== tableName && tableNames.includes(referencedTable))
      .sort((left, right) => left.localeCompare(right, 'en'));
    dependencies.set(tableName, [...new Set(referencedTables)]);
  }

  function visit(tableName: string): void {
    if (visited.has(tableName) || visiting.has(tableName)) {
      return;
    }
    visiting.add(tableName);
    for (const dependency of dependencies.get(tableName) ?? []) {
      visit(dependency);
    }
    visiting.delete(tableName);
    visited.add(tableName);
    ordered.push(tableName);
  }

  for (const tableName of tableNames) {
    visit(tableName);
  }

  return ordered;
}

function buildCreateTableStatement(
  dialect: SqlDialect,
  tableName: string,
  contract: SchemaContract,
): string {
  const table = contract.tables[tableName];
  const columnEntries = Object.entries(table.columns);
  const foreignKeys = contract.foreignKeys.filter((foreignKey) => foreignKey.table === tableName);
  const parts = [
    ...columnEntries.map(([columnName, column]) => buildColumnDefinition(dialect, columnName, column)),
    ...foreignKeys.map((foreignKey) => buildForeignKeyClause(dialect, foreignKey)),
  ];
  return `CREATE TABLE IF NOT EXISTS ${quoteIdentifier(dialect, tableName)} (${parts.join(', ')})`;
}

function buildUniqueIndexStatement(
  dialect: SqlDialect,
  uniqueIndex: SchemaContractUnique,
  contract: SchemaContract,
  options?: SqlGenerationOptions,
): string {
  const columns = uniqueIndex.columns
    .map((columnName) => {
      const suffix = dialect === 'mysql'
        ? resolveMysqlIndexPrefix(uniqueIndex.table, columnName, contract, options)
        : '';
      return `${quoteIdentifier(dialect, columnName)}${suffix}`;
    })
    .join(', ');
  return `CREATE UNIQUE INDEX ${quoteIdentifier(dialect, uniqueIndex.name)} ON ${quoteIdentifier(dialect, uniqueIndex.table)} (${columns})`;
}

function buildIndexStatement(
  dialect: SqlDialect,
  index: SchemaContractIndex,
  contract: SchemaContract,
  options?: SqlGenerationOptions,
): string {
  const columns = index.columns
    .map((columnName) => {
      const suffix = dialect === 'mysql'
        ? resolveMysqlIndexPrefix(index.table, columnName, contract, options)
        : '';
      return `${quoteIdentifier(dialect, columnName)}${suffix}`;
    })
    .join(', ');
  return `CREATE INDEX ${quoteIdentifier(dialect, index.name)} ON ${quoteIdentifier(dialect, index.table)} (${columns})`;
}

function serializeColumn(column: SchemaContractColumn): string {
  return [
    column.logicalType,
    column.notNull ? 'not-null' : 'nullable',
    column.defaultValue ?? 'default:null',
    column.primaryKey ? 'pk' : 'non-pk',
  ].join('|');
}

function serializeIndex(index: SchemaContractIndex): string {
  return [index.table, index.columns.join(','), index.unique ? 'unique' : 'non-unique'].join('|');
}

function serializeUnique(unique: SchemaContractUnique): string {
  return [unique.table, unique.columns.join(',')].join('|');
}

function serializeForeignKey(foreignKey: SchemaContractForeignKey): string {
  return [
    foreignKey.table,
    foreignKey.columns.join(','),
    foreignKey.referencedTable,
    foreignKey.referencedColumns.join(','),
    foreignKey.onDelete ?? 'null',
  ].join('|');
}

function isRouteGraphTokenRoutesReplacement(currentContract: SchemaContract, previousContract: SchemaContract): boolean {
  const previousTokenRoutes = previousContract.tables.token_routes;
  return !!previousTokenRoutes
    && !!previousTokenRoutes.columns.model_pattern
    && !!currentContract.tables.route_graph_versions
    && !!currentContract.tables.route_graph_drafts
    && !!currentContract.tables.route_graph_active_version
    && !!currentContract.tables.route_channels?.columns.route_node_id;
}

function isAllowedRouteGraphReplacementColumnRemoval(tableName: string, columnName: string): boolean {
  return tableName === 'token_routes' && (columnName === 'model_pattern' || columnName === 'route_mode' || columnName === 'match_spec' || columnName === 'backend_spec');
}

function isAllowedRouteGraphReplacementIndexRemoval(indexName: string): boolean {
  return indexName === 'token_routes_model_pattern_idx' || indexName === 'token_routes_match_spec_idx';
}

function assertAdditiveSchemaDiff(
  currentContract: SchemaContract,
  previousContract: SchemaContract,
): ControlledReplacement[] {
  const violations: string[] = [];
  const controlledReplacements: ControlledReplacement[] = [];
  const allowRouteGraphReplacement = isRouteGraphTokenRoutesReplacement(currentContract, previousContract);
  if (allowRouteGraphReplacement) {
    controlledReplacements.push('route-graph-token-routes');
  }

  for (const [tableName, previousTable] of Object.entries(previousContract.tables)) {
    const currentTable = currentContract.tables[tableName];
    if (!currentTable) {
      violations.push(`removed table ${tableName}`);
      continue;
    }

    for (const [columnName, previousColumn] of Object.entries(previousTable.columns)) {
      const currentColumn = currentTable.columns[columnName];
      if (!currentColumn) {
        if (allowRouteGraphReplacement && isAllowedRouteGraphReplacementColumnRemoval(tableName, columnName)) {
          continue;
        }
        violations.push(`removed column ${tableName}.${columnName}`);
        continue;
      }

      if (serializeColumn(currentColumn) !== serializeColumn(previousColumn)) {
        violations.push(`changed column ${tableName}.${columnName}`);
      }
    }
  }

  const currentIndexes = new Map(currentContract.indexes.map((index) => [index.name, index]));
  for (const previousIndex of previousContract.indexes) {
    const currentIndex = currentIndexes.get(previousIndex.name);
    if (!currentIndex) {
      if (allowRouteGraphReplacement && isAllowedRouteGraphReplacementIndexRemoval(previousIndex.name)) {
        continue;
      }
      violations.push(`removed index ${previousIndex.name}`);
      continue;
    }
    if (serializeIndex(currentIndex) !== serializeIndex(previousIndex)) {
      violations.push(`changed index ${previousIndex.name}`);
    }
  }

  const currentUniques = new Map(currentContract.uniques.map((unique) => [unique.name, unique]));
  for (const previousUnique of previousContract.uniques) {
    const currentUnique = currentUniques.get(previousUnique.name);
    if (!currentUnique) {
      violations.push(`removed unique ${previousUnique.name}`);
      continue;
    }
    if (serializeUnique(currentUnique) !== serializeUnique(previousUnique)) {
      violations.push(`changed unique ${previousUnique.name}`);
    }
  }

  const currentForeignKeys = new Set(currentContract.foreignKeys.map(serializeForeignKey));
  for (const previousForeignKey of previousContract.foreignKeys) {
    if (!currentForeignKeys.has(serializeForeignKey(previousForeignKey))) {
      violations.push(`removed foreign key ${previousForeignKey.table}(${previousForeignKey.columns.join(',')})`);
    }
  }

  if (violations.length > 0) {
    throw new Error(`Non-additive schema diff detected:\n- ${violations.join('\n- ')}`);
  }

  return controlledReplacements;
}

export function generateBootstrapSql(dialect: SqlDialect, contract: SchemaContract): string {
  const tableStatements = sortTableNamesForCreation(contract)
    .map((tableName) => buildCreateTableStatement(dialect, tableName, contract));

  const uniqueStatements = contract.uniques
    .slice()
    .sort((left, right) => left.name.localeCompare(right.name, 'en'))
    .map((uniqueIndex) => buildUniqueIndexStatement(dialect, uniqueIndex, contract));

  const knownUniqueNames = new Set(contract.uniques.map((uniqueIndex) => uniqueIndex.name));
  const indexStatements = contract.indexes
    .filter((index) => !knownUniqueNames.has(index.name))
    .slice()
    .sort((left, right) => left.name.localeCompare(right.name, 'en'))
    .map((index) => buildIndexStatement(dialect, index, contract));

  return `${[...tableStatements, ...uniqueStatements, ...indexStatements].join(';\n')};\n`;
}

function buildAddColumnStatement(
  dialect: SqlDialect,
  tableName: string,
  columnName: string,
  column: SchemaContractColumn,
): string {
  return `ALTER TABLE ${quoteIdentifier(dialect, tableName)} ADD COLUMN ${buildColumnDefinition(dialect, columnName, column)}`;
}

function buildRouteGraphMatchSpecExpression(dialect: Dialect, hasDisplayName: boolean): string {
  const modelPattern = quoteQualifiedIdentifier(dialect, 'token_routes', 'model_pattern');
  if (dialect === 'mysql') {
    const displayName = hasDisplayName
      ? quoteQualifiedIdentifier(dialect, 'token_routes', 'display_name')
      : 'NULL';
    return `JSON_OBJECT('kind', 'model', 'requestedModelPattern', COALESCE(${modelPattern}, ''), 'displayName', ${displayName})`;
  }

  const displayName = hasDisplayName
    ? quoteQualifiedIdentifier(dialect, 'token_routes', 'display_name')
    : 'NULL::text';
  return `jsonb_build_object('kind', 'model', 'requestedModelPattern', COALESCE(${modelPattern}, ''), 'displayName', ${displayName})::text`;
}

function buildRouteGraphBackendSpecExpression(
  dialect: Dialect,
  hasRouteMode: boolean,
  hasRouteGroupSources: boolean,
): string {
  if (!hasRouteMode) {
    return dialect === 'mysql'
      ? `JSON_OBJECT('kind', 'channels')`
      : `'{"kind":"channels"}'`;
  }

  const routeMode = quoteQualifiedIdentifier(dialect, 'token_routes', 'route_mode');
  if (dialect === 'mysql') {
    const routeIds = hasRouteGroupSources
      ? `(SELECT COALESCE(JSON_ARRAYAGG(${quoteIdentifier(dialect, 'source_route_id')}), JSON_ARRAY()) FROM ${quoteIdentifier(dialect, 'route_group_sources')} WHERE ${quoteQualifiedIdentifier(dialect, 'route_group_sources', 'group_route_id')} = ${quoteQualifiedIdentifier(dialect, 'token_routes', 'id')})`
      : 'JSON_ARRAY()';
    return `CASE WHEN ${routeMode} = 'explicit_group' THEN JSON_OBJECT('kind', 'routes', 'routeIds', ${routeIds}) ELSE JSON_OBJECT('kind', 'channels') END`;
  }

  const routeIds = hasRouteGroupSources
    ? `(SELECT COALESCE(jsonb_agg(${quoteQualifiedIdentifier(dialect, 'route_group_sources', 'source_route_id')} ORDER BY ${quoteQualifiedIdentifier(dialect, 'route_group_sources', 'source_route_id')}), '[]'::jsonb) FROM ${quoteIdentifier(dialect, 'route_group_sources')} WHERE ${quoteQualifiedIdentifier(dialect, 'route_group_sources', 'group_route_id')} = ${quoteQualifiedIdentifier(dialect, 'token_routes', 'id')})`
    : `'[]'::jsonb`;
  return `CASE WHEN ${routeMode} = 'explicit_group' THEN jsonb_build_object('kind', 'routes', 'routeIds', ${routeIds})::text ELSE '{"kind":"channels"}' END`;
}

function buildSqliteRouteGraphMatchSpecExpression(previousColumns: Record<string, SchemaContractColumn>): string {
  const hasRouteMode = !!previousColumns.route_mode;
  const hasDisplayName = !!previousColumns.display_name;
  const requestedModelPattern = hasRouteMode
    ? `CASE WHEN coalesce("token_routes"."route_mode", 'pattern') = 'explicit_group' THEN '' ELSE coalesce("token_routes"."model_pattern", '') END`
    : `coalesce("token_routes"."model_pattern", '')`;
  const displayName = hasDisplayName
    ? `CASE WHEN nullif(trim(coalesce("token_routes"."display_name", '')), '') IS NOT NULL THEN trim("token_routes"."display_name")${hasRouteMode ? ` WHEN coalesce("token_routes"."route_mode", 'pattern') = 'explicit_group' THEN coalesce("token_routes"."model_pattern", '')` : ''} ELSE NULL END`
    : hasRouteMode
      ? `CASE WHEN coalesce("token_routes"."route_mode", 'pattern') = 'explicit_group' THEN coalesce("token_routes"."model_pattern", '') ELSE NULL END`
      : 'NULL';
  return `json_object('kind', 'model', 'requestedModelPattern', ${requestedModelPattern}, 'displayName', ${displayName})`;
}

function buildSqliteRouteGraphBackendSpecExpression(
  previousColumns: Record<string, SchemaContractColumn>,
  hasRouteGroupSources: boolean,
): string {
  if (!previousColumns.route_mode) {
    return `json_object('kind', 'channels')`;
  }
  const routeIds = hasRouteGroupSources
    ? `coalesce(json((SELECT json_group_array("route_group_sources"."source_route_id") FROM "route_group_sources" WHERE "route_group_sources"."group_route_id" = "token_routes"."id" ORDER BY "route_group_sources"."source_route_id")), json('[]'))`
    : `json('[]')`;
  return `CASE WHEN coalesce("token_routes"."route_mode", 'pattern') = 'explicit_group' THEN json_object('kind', 'routes', 'routeIds', ${routeIds}) ELSE json_object('kind', 'channels') END`;
}

function buildSqliteTokenRouteValueExpression(
  columnName: string,
  previousColumns: Record<string, SchemaContractColumn>,
  hasRouteGroupSources: boolean,
): string {
  if (columnName === 'match_spec') {
    return buildSqliteRouteGraphMatchSpecExpression(previousColumns);
  }
  if (columnName === 'backend_spec') {
    return buildSqliteRouteGraphBackendSpecExpression(previousColumns, hasRouteGroupSources);
  }
  if (previousColumns[columnName]) {
    return `"token_routes"."${columnName}"`;
  }
  if (columnName === 'routing_strategy') {
    return `'weighted'`;
  }
  return 'NULL';
}

function buildSqliteRouteGraphTokenRoutesReplacementStatements(
  currentContract: SchemaContract,
  previousContract: SchemaContract,
): string[] {
  const currentTokenRoutes = currentContract.tables.token_routes;
  const previousTokenRoutes = previousContract.tables.token_routes;
  if (!currentTokenRoutes || !previousTokenRoutes?.columns.model_pattern) {
    return [];
  }

  const createTable = buildCreateTableStatement('sqlite', '__new_token_routes', {
    ...currentContract,
    tables: {
      __new_token_routes: currentTokenRoutes,
    },
    foreignKeys: currentContract.foreignKeys
      .filter((foreignKey) => foreignKey.table === 'token_routes')
      .map((foreignKey) => ({ ...foreignKey, table: '__new_token_routes' })),
  });
  const columnNames = Object.keys(currentTokenRoutes.columns);
  const quotedColumns = columnNames.map((columnName) => `"${columnName}"`).join(', ');
  const expressions = columnNames
    .map((columnName) => buildSqliteTokenRouteValueExpression(
      columnName,
      previousTokenRoutes.columns,
      !!previousContract.tables.route_group_sources,
    ))
    .join(', ');

  const statements = [
    createTable.replace('CREATE TABLE IF NOT EXISTS', 'CREATE TABLE'),
    `INSERT INTO "__new_token_routes" (${quotedColumns}) SELECT ${expressions} FROM "token_routes"`,
    'DROP TABLE "token_routes"',
    'ALTER TABLE "__new_token_routes" RENAME TO "token_routes"',
  ];

  for (const index of currentContract.indexes
    .filter((item) => item.table === 'token_routes')
    .sort((left, right) => left.name.localeCompare(right.name, 'en'))) {
    statements.push(buildIndexStatement('sqlite', index, currentContract));
  }
  for (const unique of currentContract.uniques
    .filter((item) => item.table === 'token_routes')
    .sort((left, right) => left.name.localeCompare(right.name, 'en'))) {
    statements.push(buildUniqueIndexStatement('sqlite', unique, currentContract));
  }

  return statements;
}

function buildRouteGraphTokenRoutesReplacementStatements(
  dialect: SqlDialect,
  currentContract: SchemaContract,
  previousContract: SchemaContract,
  options?: SqlGenerationOptions,
): string[] {
  if (dialect === 'sqlite') {
    return buildSqliteRouteGraphTokenRoutesReplacementStatements(currentContract, previousContract);
  }

  const previousTokenRoutes = previousContract.tables.token_routes;
  if (!previousTokenRoutes?.columns.model_pattern) {
    return [];
  }

  const statements: string[] = [];
  if (dialect === 'mysql') {
    if (previousContract.indexes.some((index) => index.name === 'token_routes_model_pattern_idx')) {
      statements.push('DROP INDEX `token_routes_model_pattern_idx` ON `token_routes`');
    }
    statements.push('ALTER TABLE `token_routes` DROP COLUMN `model_pattern`');
    if (previousTokenRoutes.columns.route_mode) {
      statements.push('ALTER TABLE `token_routes` DROP COLUMN `route_mode`');
    }
    if (previousTokenRoutes.columns.match_spec) {
      statements.push('ALTER TABLE `token_routes` DROP COLUMN `match_spec`');
    }
    if (previousTokenRoutes.columns.backend_spec) {
      statements.push('ALTER TABLE `token_routes` DROP COLUMN `backend_spec`');
    }
  } else {
    if (previousContract.indexes.some((index) => index.name === 'token_routes_model_pattern_idx')) {
      statements.push('DROP INDEX IF EXISTS "token_routes_model_pattern_idx"');
    }
    statements.push('ALTER TABLE "token_routes" DROP COLUMN "model_pattern"');
    if (previousTokenRoutes.columns.route_mode) {
      statements.push('ALTER TABLE "token_routes" DROP COLUMN "route_mode"');
    }
    if (previousTokenRoutes.columns.match_spec) {
      statements.push('ALTER TABLE "token_routes" DROP COLUMN "match_spec"');
    }
    if (previousTokenRoutes.columns.backend_spec) {
      statements.push('ALTER TABLE "token_routes" DROP COLUMN "backend_spec"');
    }
  }

  return statements;
}

export function generateUpgradeSql(
  dialect: SqlDialect,
  currentContract: SchemaContract,
  previousContract?: SchemaContract | null,
  options?: SqlGenerationOptions,
): string {
  if (!previousContract) {
    return `-- no previous schema contract available for ${dialect} additive upgrade generation\n`;
  }

  const controlledReplacements = assertAdditiveSchemaDiff(currentContract, previousContract);
  const hasRouteGraphReplacement = controlledReplacements.includes('route-graph-token-routes');

  const previousTableNames = new Set(Object.keys(previousContract.tables));
  const currentTableNames = Object.keys(currentContract.tables).sort((left, right) => left.localeCompare(right, 'en'));
  const addedTableNames = currentTableNames.filter((tableName) => !previousTableNames.has(tableName));
  const addedTablesContract: SchemaContract = {
    tables: Object.fromEntries(addedTableNames.map((tableName) => [tableName, currentContract.tables[tableName]])),
    indexes: currentContract.indexes.filter((index) => addedTableNames.includes(index.table)),
    uniques: currentContract.uniques.filter((unique) => addedTableNames.includes(unique.table)),
    foreignKeys: currentContract.foreignKeys.filter((foreignKey) => addedTableNames.includes(foreignKey.table)),
  };
  const addedTableStatements = sortTableNamesForCreation(addedTablesContract)
    .map((tableName) => buildCreateTableStatement(dialect, tableName, currentContract));

  const addColumnStatements: string[] = [];
  for (const tableName of currentTableNames) {
    if (!previousTableNames.has(tableName)) {
      continue;
    }

    const previousColumns = previousContract.tables[tableName]?.columns ?? {};
    const currentColumns = currentContract.tables[tableName]?.columns ?? {};
    for (const [columnName, column] of Object.entries(currentColumns)) {
      if (previousColumns[columnName]) {
        continue;
      }
      if (
        hasRouteGraphReplacement
        && tableName === 'token_routes'
        && (columnName === 'match_spec' || columnName === 'backend_spec')
      ) {
        continue;
      }
      addColumnStatements.push(buildAddColumnStatement(dialect, tableName, columnName, column));
    }
  }

  const previousUniqueNames = new Set(previousContract.uniques.map((unique) => unique.name));
  const uniqueStatements = currentContract.uniques
    .filter((unique) => !previousUniqueNames.has(unique.name))
    .slice()
    .sort((left, right) => left.name.localeCompare(right.name, 'en'))
    .map((unique) => buildUniqueIndexStatement(dialect, unique, currentContract, options));

  const currentUniqueNames = new Set(currentContract.uniques.map((unique) => unique.name));
  const previousIndexNames = new Set(previousContract.indexes.map((index) => index.name));
  const indexStatements = currentContract.indexes
    .filter((index) => !currentUniqueNames.has(index.name))
    .filter((index) => !previousIndexNames.has(index.name))
    .filter((index) => !(hasRouteGraphReplacement && index.name === 'token_routes_match_spec_idx'))
    .slice()
    .sort((left, right) => left.name.localeCompare(right.name, 'en'))
    .map((index) => buildIndexStatement(dialect, index, currentContract, options));

  const replacementStatements = hasRouteGraphReplacement
    ? buildRouteGraphTokenRoutesReplacementStatements(dialect, currentContract, previousContract, options)
    : [];
  const statements = [...addedTableStatements, ...addColumnStatements, ...replacementStatements, ...uniqueStatements, ...indexStatements];
  if (statements.length === 0) {
    return `-- no schema changes detected for ${dialect}\n`;
  }

  return `${statements.join(';\n')};\n`;
}

export function generateDialectArtifacts(
  contract: SchemaContract,
  previousContract?: SchemaContract | null,
): GeneratedDialectArtifacts {
  return {
    mysqlBootstrap: generateBootstrapSql('mysql', contract),
    postgresBootstrap: generateBootstrapSql('postgres', contract),
    mysqlUpgrade: generateUpgradeSql('mysql', contract, previousContract),
    postgresUpgrade: generateUpgradeSql('postgres', contract, previousContract),
  };
}

export function writeDialectArtifactFiles(
  contract: SchemaContract,
  previousContract?: SchemaContract | null,
): GeneratedDialectArtifacts {
  const artifacts = generateDialectArtifacts(contract, previousContract);
  const artifactEntries = [
    ['mysql.bootstrap.sql', artifacts.mysqlBootstrap],
    ['postgres.bootstrap.sql', artifacts.postgresBootstrap],
    ['mysql.upgrade.sql', artifacts.mysqlUpgrade],
    ['postgres.upgrade.sql', artifacts.postgresUpgrade],
  ] as const;

  for (const [filename, content] of artifactEntries) {
    const outputPath = resolveGeneratedArtifactPath(filename);
    mkdirSync(dirname(outputPath), { recursive: true });
    writeFileSync(outputPath, content, 'utf8');
  }

  return artifacts;
}
