import { macroFlowNodeId } from './routeGraphConnections.js';
import { getNodePorts } from './routeGraphRegistry.js';
import { tr } from '../../i18n.js';
import type { RouteGraphEdge, RouteGraphMacro, RouteGraphNode, RouteGraphOwnership, RouteGraphPort, RouteGraphPortKind } from './routeGraphTypes.js';
import type { RouteEndpointCatalogItem } from './types.js';

export type RouteGraphLike = {
  nodes: RouteGraphNode[];
  edges: RouteGraphEdge[];
  macros?: RouteGraphMacro[];
};

export function getNodeTitle(node: RouteGraphNode): string {
  return String(node.name || node.id);
}

export function getNodeStatusLabel(node: RouteGraphNode): 'enabled' | 'disabled' {
  return node.enabled ? 'enabled' : 'disabled';
}

function formatCount(key: string, count: number): string {
  return tr(key).replace('{count}', String(count));
}

function formatValue(key: string, replacements: Record<string, string | number>): string {
  let value = tr(key);
  for (const [name, replacement] of Object.entries(replacements)) {
    value = value.replace(`{${name}}`, String(replacement));
  }
  return value;
}

const ownershipLabelKeys: Record<RouteGraphOwnership, string> = {
  manual: 'pages.tokenRoutes.routeGraphViewModel.ownership.manual',
  auto_generated: 'pages.tokenRoutes.routeGraphViewModel.ownership.autoGenerated',
  system: 'pages.tokenRoutes.routeGraphViewModel.ownership.system',
  derived: 'pages.tokenRoutes.routeGraphViewModel.ownership.derived',
};

const visibilityLabelKeys: Record<RouteGraphNode['visibility'], string> = {
  public: 'pages.tokenRoutes.routeGraphViewModel.visibility.public',
  internal: 'pages.tokenRoutes.routeGraphViewModel.visibility.internal',
};

const statusLabelKeys: Record<ReturnType<typeof getNodeStatusLabel>, string> = {
  enabled: 'pages.tokenRoutes.routeGraphViewModel.status.enabled',
  disabled: 'pages.tokenRoutes.routeGraphViewModel.status.disabled',
};

const portDirectionLabelKeys: Record<RouteGraphPort['direction'], string> = {
  input: 'pages.tokenRoutes.routeGraphViewModel.portDirection.input',
  output: 'pages.tokenRoutes.routeGraphViewModel.portDirection.output',
};

const portKindLabelKeys: Record<RouteGraphPortKind, string> = {
  request: 'pages.tokenRoutes.routeGraphViewModel.portKind.request',
  bidirect: 'pages.tokenRoutes.routeGraphViewModel.portKind.bidirect',
  route: 'pages.tokenRoutes.routeGraphViewModel.portKind.route',
  response: 'pages.tokenRoutes.routeGraphViewModel.portKind.response',
  control: 'pages.tokenRoutes.routeGraphViewModel.portKind.control',
  metrics: 'pages.tokenRoutes.routeGraphViewModel.portKind.metrics',
};

const nodeTypeLabelKeys: Record<RouteGraphNode['type'], string> = {
  entry: 'pages.tokenRoutes.routeGraphViewModel.nodeType.entry',
  route_endpoint: 'pages.tokenRoutes.routeGraphViewModel.nodeType.routeEndpoint',
  filter: 'pages.tokenRoutes.routeGraphViewModel.nodeType.filter',
  dispatcher: 'pages.tokenRoutes.routeGraphViewModel.nodeType.dispatcher',
  synthetic_endpoint: 'pages.tokenRoutes.routeGraphViewModel.nodeType.syntheticEndpoint',
  auto_node: 'pages.tokenRoutes.routeGraphViewModel.nodeType.autoNode',
};

const dispatcherModeLabelKeys: Record<string, string> = {
  route: 'pages.tokenRoutes.routeGraphViewModel.dispatcherMode.route',
  flow: 'pages.tokenRoutes.routeGraphViewModel.dispatcherMode.flow',
};

const endpointKindLabelKeys: Record<string, string> = {
  supply: 'pages.tokenRoutes.routeGraphViewModel.endpointKind.supply',
  route_product: 'pages.tokenRoutes.routeGraphViewModel.endpointKind.routeProduct',
};

const ownerKindLabelKeys: Record<string, string> = {
  macro: 'pages.tokenRoutes.routeGraphViewModel.ownerKind.macro',
  manual_route: 'pages.tokenRoutes.routeGraphViewModel.ownerKind.manualRoute',
  automatic_model_group: 'pages.tokenRoutes.routeGraphViewModel.ownerKind.automaticModelGroup',
  upstream_model: 'pages.tokenRoutes.routeGraphViewModel.ownerKind.upstreamModel',
};

function getMappedLabel(map: Partial<Record<string, string>>, value: unknown): string {
  const key = String(value || '').trim();
  return key && map[key] ? tr(map[key]) : key.replace(/_/g, ' ');
}

function getOwnershipLabel(value: RouteGraphOwnership): string {
  return tr(ownershipLabelKeys[value]);
}

function getStatusDisplayLabel(value: ReturnType<typeof getNodeStatusLabel>): string {
  return tr(statusLabelKeys[value]);
}

function getVisibilityLabel(value: RouteGraphNode['visibility']): string {
  return tr(visibilityLabelKeys[value]);
}

function getNodeTypeLabel(value: RouteGraphNode['type']): string {
  return tr(nodeTypeLabelKeys[value]);
}

function getDispatcherModeLabel(value: unknown): string {
  return getMappedLabel(dispatcherModeLabelKeys, value || 'route');
}

function getEndpointKindLabel(value: unknown): string {
  return getMappedLabel(endpointKindLabelKeys, value);
}

export function getNodeCardSubtitle(node: RouteGraphNode): string {
  if (node.type === 'entry') {
    const match = (node.match || {}) as Record<string, unknown>;
    return String(match.displayName || match.requestedModelPattern || tr('pages.tokenRoutes.routeGraphViewModel.publicModelEntry'));
  }
  if (node.type === 'dispatcher') {
    return formatValue('pages.tokenRoutes.routeGraphViewModel.dispatcherSubtitle', {
      mode: getDispatcherModeLabel(node.mode || 'route'),
    });
  }
  if (node.type === 'route_endpoint') {
    const config = (node.config || {}) as { targets?: unknown[] };
    const targetCount = Array.isArray(config.targets) ? config.targets.length : 0;
    const kind = String(node.endpointKind || (targetCount > 0 ? 'supply' : 'route_product'));
    const exposure = String(node.exposure || (kind === 'supply' ? 'none' : node.visibility));
    if (kind === 'supply') {
      return targetCount === 1
        ? tr('pages.tokenRoutes.routeGraphViewModel.oneUpstreamTarget')
        : formatCount('pages.tokenRoutes.routeGraphViewModel.upstreamTargetsCount', targetCount);
    }
    return `${getEndpointKindLabel(kind)} · ${getMappedLabel(visibilityLabelKeys, exposure) || exposure}`;
  }
  if (node.type === 'filter') {
    const count = Array.isArray(node.operations) ? node.operations.length : 0;
    return count === 1
      ? tr('pages.tokenRoutes.routeGraphViewModel.oneOperation')
      : formatCount('pages.tokenRoutes.routeGraphViewModel.operationsCount', count);
  }
  if (node.type === 'synthetic_endpoint') {
    return formatValue('pages.tokenRoutes.routeGraphViewModel.syntheticResponse', {
      status: String(node.statusCode || 503),
    });
  }
  return formatValue('pages.tokenRoutes.routeGraphViewModel.ownershipNode', {
    ownership: getOwnershipLabel(node.ownership),
  });
}

export function getNodeCardMetrics(graph: RouteGraphLike, node: RouteGraphNode): string[] {
  const metrics: string[] = [];
  const connectionCount = getNodeConnectionCount(graph, node.id);
  metrics.push(connectionCount === 1
    ? tr('pages.tokenRoutes.routeGraphViewModel.oneConnection')
    : formatCount('pages.tokenRoutes.routeGraphViewModel.connectionsCount', connectionCount));
  if (typeof node.successRate === 'number') {
    metrics.push(formatValue('pages.tokenRoutes.routeGraphViewModel.successPercent', {
      percent: Math.round(node.successRate * 100),
    }));
  }
  if (node.type === 'dispatcher') metrics.push(String(node.policy && typeof node.policy === 'object' && 'strategy' in node.policy ? (node.policy as any).strategy : 'weighted'));
  return metrics;
}

export function getNodeSubtitle(node: RouteGraphNode): string {
  return node.id;
}

export function getNodeModeLabel(node: RouteGraphNode): string {
  return node.type === 'dispatcher' ? String(node.mode || 'route') : 'n/a';
}

export function getPublicEntryCount(graph: RouteGraphLike): number {
  return getPublicEntryNodes(graph).length;
}

export function getPublicEntryNodes(graph: RouteGraphLike): RouteGraphNode[] {
  return graph.nodes.filter((node) => node.type === 'entry' && node.visibility === 'public');
}

export type PublicModelEntryRow = {
  id: string;
  nodeId: string;
  title: string;
  subtitle: string;
  source: 'compiled_endpoint' | 'entry_node' | 'macro_entry';
};

function formatPublicModelCatalogSubtitle(endpoint: RouteEndpointCatalogItem): string {
  const parts = [
    getMappedLabel(ownerKindLabelKeys, endpoint.ownerKind),
    endpoint.siteNames.slice(0, 2).join(', '),
    endpoint.sourceRouteIds && endpoint.sourceRouteIds.length > 0
      ? formatCount('pages.tokenRoutes.routeGraphViewModel.routesCount', endpoint.sourceRouteIds.length)
      : '',
    endpoint.endpointId,
  ].filter(Boolean);
  return parts.join(' · ');
}

function getRecordValue(value: unknown): Record<string, unknown> | null {
  return value && typeof value === 'object' && !Array.isArray(value) ? value as Record<string, unknown> : null;
}

function getPublicEntryNodeTitle(node: RouteGraphNode): string {
  const match = (node.match || {}) as Record<string, unknown>;
  return String(match.displayName || match.requestedModelPattern || getNodeTitle(node)).trim();
}

function getConfiguredPublicMacroEntry(macro: RouteGraphMacro): PublicModelEntryRow | null {
  if (macro.kind !== 'candidate_selector') return null;
  const config = getRecordValue(macro.config);
  const surface = getRecordValue(config?.surface);
  const entry = getRecordValue(surface?.entry);
  if (!entry || entry.kind !== 'external' || entry.visibility !== 'public') return null;
  const match = getRecordValue(entry.match);
  const title = String(match?.displayName || match?.requestedModelPattern || macro.name || macro.id).trim();
  if (!title) return null;
  const enabled = macro.enabled !== false;
  return {
    id: enabled ? `macro:${macro.id}:entry` : `macro-config:${macro.id}:entry`,
    nodeId: enabled ? `macro:${macro.id}:entry` : macroFlowNodeId(macro.id),
    title,
    subtitle: `${enabled ? '' : `${tr('pages.tokenRoutes.routeGraphViewModel.status.disabled')} · `}${tr('pages.tokenRoutes.routeGraphViewModel.ownerKind.macro')} · ${macro.id}`,
    source: 'macro_entry',
  };
}

export function getPublicModelEntryRows(
  graph: RouteGraphLike,
  endpointCatalog: RouteEndpointCatalogItem[] = [],
): PublicModelEntryRow[] {
  const rows = new Map<string, PublicModelEntryRow>();
  const seenTitles = new Set<string>();

  for (const endpoint of endpointCatalog) {
    if (endpoint.enabled === false) continue;
    if (endpoint.endpointKind !== 'route_product') continue;
    if (endpoint.exposure !== 'public') continue;
    if (endpoint.resolutionStatus === 'unresolved') continue;
    const title = String(endpoint.publicModelName || endpoint.modelPattern || endpoint.label || '').trim();
    if (!title) continue;
    const titleKey = title.toLowerCase();
    seenTitles.add(titleKey);
    rows.set(`endpoint:${endpoint.endpointId}`, {
      id: endpoint.endpointId,
      nodeId: endpoint.nodeId || endpoint.endpointId,
      title,
      subtitle: formatPublicModelCatalogSubtitle(endpoint),
      source: 'compiled_endpoint',
    });
  }

  for (const node of getPublicEntryNodes(graph)) {
    const title = getPublicEntryNodeTitle(node);
    if (!title) continue;
    const titleKey = title.toLowerCase();
    if (seenTitles.has(titleKey)) continue;
    seenTitles.add(titleKey);
    rows.set(`node:${node.id}`, {
      id: node.id,
      nodeId: node.id,
      title,
      subtitle: getModelListSubtitle(node),
      source: 'entry_node',
    });
  }

  for (const macro of graph.macros || []) {
    const row = getConfiguredPublicMacroEntry(macro);
    if (!row) continue;
    const titleKey = row.title.toLowerCase();
    if (seenTitles.has(titleKey)) continue;
    seenTitles.add(titleKey);
    rows.set(row.id, row);
  }

  return Array.from(rows.values()).sort((left, right) => {
    const titleOrder = left.title.localeCompare(right.title);
    return titleOrder || left.id.localeCompare(right.id);
  });
}

export function filterPublicModelEntryRows(rows: PublicModelEntryRow[], query: string): PublicModelEntryRow[] {
  const terms = query
    .trim()
    .toLowerCase()
    .split(/\s+/)
    .filter(Boolean);
  if (terms.length === 0) return rows;
  return rows.filter((row) => {
    const haystack = [
      row.title,
      row.subtitle,
      row.id,
      row.nodeId,
      row.source,
    ].join(' ').toLowerCase();
    return terms.every((term) => haystack.includes(term));
  });
}

export function getManualNodeCount(graph: RouteGraphLike): number {
  return graph.nodes.filter((node) => node.ownership === 'manual').length;
}

export function getNodeConnectionCount(graph: RouteGraphLike, nodeId: string): number {
  return graph.edges.filter((edge) => edge.sourceNodeId === nodeId || edge.targetNodeId === nodeId).length;
}

export function getPortConnectionCount(graph: RouteGraphLike, nodeId: string, portId: string): number {
  return graph.edges.filter((edge) => (
    (edge.sourceNodeId === nodeId && edge.sourcePortId === portId)
    || (edge.targetNodeId === nodeId && edge.targetPortId === portId)
  )).length;
}

export function getPortSummary(port: RouteGraphPort): string {
  return [
    tr(portDirectionLabelKeys[port.direction]),
    tr(portKindLabelKeys[port.kind]),
    port.required ? tr('pages.tokenRoutes.routeGraphViewModel.required') : '',
  ].filter(Boolean).join(' · ');
}

const portLabelKeys: Record<string, { single: string; plural: string }> = {
  'reuse input': {
    single: 'pages.tokenRoutes.routeGraphViewModel.portLabel.reuseInput',
    plural: 'pages.tokenRoutes.routeGraphViewModel.portLabel.reuseInputs',
  },
  'matched flow': {
    single: 'pages.tokenRoutes.routeGraphViewModel.portLabel.matchedFlow',
    plural: 'pages.tokenRoutes.routeGraphViewModel.portLabel.matchedFlows',
  },
  'before mutation': {
    single: 'pages.tokenRoutes.routeGraphViewModel.portLabel.beforeMutation',
    plural: 'pages.tokenRoutes.routeGraphViewModel.portLabel.beforeMutations',
  },
  'after mutation': {
    single: 'pages.tokenRoutes.routeGraphViewModel.portLabel.afterMutation',
    plural: 'pages.tokenRoutes.routeGraphViewModel.portLabel.afterMutations',
  },
  'before round trip': {
    single: 'pages.tokenRoutes.routeGraphViewModel.portLabel.beforeRoundTrip',
    plural: 'pages.tokenRoutes.routeGraphViewModel.portLabel.beforeRoundTrips',
  },
  'after round trip': {
    single: 'pages.tokenRoutes.routeGraphViewModel.portLabel.afterRoundTrip',
    plural: 'pages.tokenRoutes.routeGraphViewModel.portLabel.afterRoundTrips',
  },
  'dispatch input': {
    single: 'pages.tokenRoutes.routeGraphViewModel.portLabel.dispatchInput',
    plural: 'pages.tokenRoutes.routeGraphViewModel.portLabel.dispatchInputs',
  },
  'dispatch path': {
    single: 'pages.tokenRoutes.routeGraphViewModel.portLabel.dispatchPath',
    plural: 'pages.tokenRoutes.routeGraphViewModel.portLabel.dispatchPaths',
  },
  'endpoint candidates': {
    single: 'pages.tokenRoutes.routeGraphViewModel.portLabel.endpointCandidates',
    plural: 'pages.tokenRoutes.routeGraphViewModel.portLabel.endpointCandidates',
  },
  'route product': {
    single: 'pages.tokenRoutes.routeGraphViewModel.portLabel.routeProduct',
    plural: 'pages.tokenRoutes.routeGraphViewModel.portLabel.routeProducts',
  },
  'invoke route': {
    single: 'pages.tokenRoutes.routeGraphViewModel.portLabel.invokeRoute',
    plural: 'pages.tokenRoutes.routeGraphViewModel.portLabel.invokeRoutes',
  },
  'synthetic target': {
    single: 'pages.tokenRoutes.routeGraphViewModel.portLabel.syntheticTarget',
    plural: 'pages.tokenRoutes.routeGraphViewModel.portLabel.syntheticTargets',
  },
  'return response': {
    single: 'pages.tokenRoutes.routeGraphViewModel.portLabel.returnResponse',
    plural: 'pages.tokenRoutes.routeGraphViewModel.portLabel.returnResponses',
  },
  'candidate targets': {
    single: 'pages.tokenRoutes.routeGraphViewModel.portLabel.candidateTargets',
    plural: 'pages.tokenRoutes.routeGraphViewModel.portLabel.candidateTargets',
  },
  'route input': {
    single: 'pages.tokenRoutes.routeGraphViewModel.portLabel.routeInput',
    plural: 'pages.tokenRoutes.routeGraphViewModel.portLabel.routeInputs',
  },
  'selected path': {
    single: 'pages.tokenRoutes.routeGraphViewModel.portLabel.selectedPath',
    plural: 'pages.tokenRoutes.routeGraphViewModel.portLabel.selectedPaths',
  },
  'request fallback': {
    single: 'pages.tokenRoutes.routeGraphViewModel.portLabel.requestFallback',
    plural: 'pages.tokenRoutes.routeGraphViewModel.portLabel.requestFallbacks',
  },
  response: {
    single: 'pages.tokenRoutes.routeGraphViewModel.portLabel.response',
    plural: 'pages.tokenRoutes.routeGraphViewModel.portLabel.responses',
  },
  route: {
    single: 'pages.tokenRoutes.routeGraphViewModel.portLabel.route',
    plural: 'pages.tokenRoutes.routeGraphViewModel.portLabel.routes',
  },
  request: {
    single: 'pages.tokenRoutes.routeGraphViewModel.portLabel.request',
    plural: 'pages.tokenRoutes.routeGraphViewModel.portLabel.requests',
  },
  error: {
    single: 'pages.tokenRoutes.routeGraphViewModel.portLabel.error',
    plural: 'pages.tokenRoutes.routeGraphViewModel.portLabel.errors',
  },
  'endpoint target': {
    single: 'pages.tokenRoutes.routeGraphViewModel.portLabel.endpointTarget',
    plural: 'pages.tokenRoutes.routeGraphViewModel.portLabel.endpointTargets',
  },
};

function getKnownPortLabel(label: string, cardinality: 'single' | 'plural'): string | null {
  const key = portLabelKeys[label]?.[cardinality];
  return key ? tr(key) : null;
}

export function pluralizePortLabel(label: string): string {
  const known = getKnownPortLabel(label, 'plural');
  if (known) return known;
  if (label.endsWith('s')) return label;
  if (label === 'request fallback') return 'request fallbacks';
  if (label === 'response') return 'responses';
  if (label === 'route') return 'routes';
  if (label === 'request') return 'requests';
  if (label === 'error') return 'errors';
  if (label === 'matched flow') return 'matched flows';
  if (label === 'dispatch path') return 'dispatch paths';
  if (label === 'endpoint target') return 'endpoint targets';
  if (label === 'synthetic target') return 'synthetic targets';
  if (label === 'selected path') return 'selected paths';
  return `${label}s`;
}

export function getPortDisplayLabel(port: RouteGraphPort): string {
  if (port.direction === 'input') return getKnownPortLabel(port.label, 'single') || port.label;
  return pluralizePortLabel(port.label);
}

export function getPortCollectionKind(port: RouteGraphPort): 'single' | 'arr' | 'set' {
  return port.collection?.type || 'single';
}

export function getPortTypeSignature(port: RouteGraphPort): string {
  const collection = port.collection;
  if (!collection || collection.type === 'single') return port.kind;
  const open = collection.type === 'set' ? '{' : '[';
  const close = collection.type === 'set' ? '}' : ']';
  const min = typeof collection.min === 'number' ? String(collection.min) : '';
  const max = typeof collection.max === 'number' ? String(collection.max) : '';
  if (!min && !max) return `${port.kind}${open}${close}`;
  return `${port.kind}${open}${min},${max}${close}`;
}

export function getPortModeNote(node: RouteGraphNode, port: RouteGraphPort): string | null {
  if (node.type !== 'dispatcher') return null;
  if (port.id === 'route.in' && node.mode === 'flow') return tr('pages.tokenRoutes.routeGraphViewModel.ignoredInFlowMode');
  if (port.id === 'bidirect[1...].out' && node.mode !== 'flow') return tr('pages.tokenRoutes.routeGraphViewModel.ignoredInRouteMode');
  return null;
}

export function getNodePortsPreview(node: RouteGraphNode, limit = 5): RouteGraphPort[] {
  return getNodePorts(node).slice(0, limit);
}

export function getNodeConnections(graph: RouteGraphLike, nodeId: string): Array<{ edge: RouteGraphEdge; direction: 'inbound' | 'outbound'; peerNodeId: string }> {
  const connections: Array<{ edge: RouteGraphEdge; direction: 'inbound' | 'outbound'; peerNodeId: string }> = [];
  for (const edge of graph.edges) {
    if (edge.sourceNodeId === nodeId) connections.push({ edge, direction: 'outbound', peerNodeId: edge.targetNodeId });
    if (edge.targetNodeId === nodeId) connections.push({ edge, direction: 'inbound', peerNodeId: edge.sourceNodeId });
  }
  return connections;
}

export function getNodeInspectorFacts(graph: RouteGraphLike, node: RouteGraphNode): Array<{ label: string; value: string | number }> {
  return [
    { label: tr('pages.tokenRoutes.routeGraphViewModel.fact.selected'), value: node.id },
    { label: tr('pages.tokenRoutes.routeGraphViewModel.fact.type'), value: getNodeTypeLabel(node.type) },
    { label: tr('pages.tokenRoutes.routeGraphViewModel.fact.mode'), value: getNodeModeLabel(node) },
    { label: tr('pages.tokenRoutes.routeGraphViewModel.fact.connections'), value: getNodeConnectionCount(graph, node.id) },
  ];
}

export function getGraphFacts(graph: RouteGraphLike): Array<{ label: string; value: string | number }> {
  return [
    { label: tr('pages.tokenRoutes.routeGraphViewModel.fact.nodes'), value: graph.nodes.length },
    { label: tr('pages.tokenRoutes.routeGraphViewModel.fact.edges'), value: graph.edges.length },
    { label: tr('pages.tokenRoutes.routeGraphViewModel.fact.public'), value: getPublicEntryCount(graph) },
    { label: tr('pages.tokenRoutes.routeGraphViewModel.fact.manual'), value: getManualNodeCount(graph) },
  ];
}

export function getModelListSubtitle(node: RouteGraphNode): string {
  return `${getStatusDisplayLabel(getNodeStatusLabel(node))} · ${getOwnershipLabel(node.ownership)}`;
}

export function getOutlineSubtitle(node: RouteGraphNode): string {
  return `${getNodeTypeLabel(node.type)} · ${getVisibilityLabel(node.visibility)} · ${getOwnershipLabel(node.ownership)}`;
}
